### ISSUE TITLE
Schema default value is not taken into account

### ISSUE THREAD

**Issue by przwoj01** [flix-tech/avro-serde-php#53] opened 2021-02-04 12:21 UTC
Code snipped below doesn't work. 
`$dataWriter->append(...);` seems to not process default value. 

Isn't it expected to contain "married" field with "null" value in encoded string? It throws `AvroIOTypeException` instead

```
$schema = <<<_JSON
{
 "name":"member",
 "type":"record",
 "fields":[
    {"name": "member_id", "type": "int"},
    {"name": "member_name", "type": "string"},
    {"name": "married", "type": ["null","boolean"], "default": null}
 ]
}
_JSON;

$jose = [
    'member_id' => 1392,
    'member_name' => 'Jose',
    //    'married' => true
];

$writerSchema = AvroSchema::parse($schema);
$io = new AvroStringIO();
$writer = new AvroIODatumWriter($writerSchema);
$dataWriter = new AvroDataIOWriter($io, $writer, $writerSchema);
$dataWriter->append($jose);
$dataWriter->close();
echo $binaryString = $io->string();
```

**Comment by Necsord** [comment] 2021-04-19 12:03
Came across the same issue and found related [issue](https://github.com/researchgate/avro-php/pull/3). It was already fixed and merged but [forked library](https://github.com/flix-tech/avro-php) being used is outdated. Can someone merge the changes?

**Comment by mente** [comment] 2021-05-17 15:57
Thanks for reporting. PRs are welcome to the library. I will review them in timely manner. Please include a test case reproduce with it.  @przwoj01  it looks like you already have one

**Closed** 2021-08-23 23:34 UTC
Labels: bug
